[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#12151a"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#12151a"
foreground = "#d8dee9"

[font]
size = 12

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "PageUp"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "PageDown"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Home"
mods = "Control|Shift"

[scrolling]
history = 5000

[window]
opacity = 0.9

[window.dimensions]
columns = 120
lines = 34

[window.padding]
x = 8
y = 8
